---
# ------------------------------------------------
# VirtualMachine for scanning
# ------------------------------------------------
ocp4_workload_rhacs_demo_vm_name: rhel
ocp4_workload_rhacs_demo_vm_namespace: rhelvm
ocp4_workload_rhacs_demo_vm_datasource_name: rhel10
ocp4_workload_rhacs_demo_vm_datasource_namespace: openshift-virtualization-os-images
ocp4_workload_rhacs_demo_vm_user: rhel
ocp4_workload_rhacs_demo_vm_password: ""
ocp4_workload_rhacs_demo_vm_ssh_pwauth: true
ocp4_workload_rhacs_demo_vm_disksize: 30Gi
ocp4_workload_rhacs_demo_vm_cpu_cores: 1
ocp4_workload_rhacs_demo_vm_cpu_sockets: 1
ocp4_workload_rhacs_demo_vm_cpu_threads: 1
ocp4_workload_rhacs_demo_vm_memory_guest: 2Gi
# Set via config. No script run if empty
ocp4_workload_rhacs_demo_vm_init_script_url: ""

# A satellite server to register the VM with
ocp4_workload_rhacs_demo_vm_satellite_url: ""
ocp4_workload_rhacs_demo_vm_satellite_org: ""
ocp4_workload_rhacs_demo_vm_satellite_activationkey: ""
