---
- name: Set cluster API context
  ansible.builtin.include_role:
    name: troshka_workload_cclm_common
    tasks_from: set_cluster_context.yml

- name: Create Submariner broker on {{ cclm_cluster_name }}
  kubernetes.core.k8s:
    host: "{{ cclm_k8s_host }}"
    api_key: "{{ cclm_k8s_token }}"
    validate_certs: "{{ cclm_k8s_validate_certs }}"
    state: present
    definition:
      apiVersion: submariner.io/v1alpha1
      kind: Broker
      metadata:
        name: "{{ cclm_submariner_broker_name }}"
        namespace: "{{ cclm_submariner_broker_namespace }}"
